/* form_style.js должен быть выполнен перед form_validation.js */
@@include('animation_css_extend.js')
@@include('form_style.js')
@@include('label_animation.js')
@@include('form_validation.js')
@@include('form_mask.js')
@@include('update_svg.js')
@@include('datepicker.js')
@@include('tab_switcher.js')
@@include('visibility_control.js')
@@include('range_slider.js')
@@include('header_fixed.js')
@@include('slick.js')
@@include('persons.js')
@@include('tab.js')
@@include('modal.js')
@@include('doc.js')
@@include('anchor.js')
@@include('scroll.js')
@@include('active_item.js')
@@include('slider.js')
@@include('intro_cases.js')
@@include('header_fixed.js')

